spring:
  application:
    name: devho
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 28f9c414aad345b18a52dc62a3373603
            client-secret: 2d79ffccdd762489eb43c16413922309
            redirect-uri: http://localhost:8080/kakao/auth/proc
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sodam?serverTime=Asia/Seoul
    username: root
    password: Cv93523827!!


    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
      minimum-idle: 5
      maximum-pool-size: 20


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    show-sql: true
  aop:
    auto: true
    proxy-target-class: true