# 개발 환경 설정
spring:
  profiles:
    active: dev

  # 개발 환경 데이터베이스 설정
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/sodam_dev?serverTime=Asia/Seoul&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:#{null}}
    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
      minimum-idle: 2                     # 개발 환경에서는 적은 연결 수
      maximum-pool-size: 5                # 개발 환경에서는 적은 연결 수
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: SodamDevHikariPool

  # 개발 환경 JPA 설정
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}   # 개발 환경에서는 create-drop 사용
    properties:
      hibernate:
        format_sql: true                  # 개발 환경에서는 SQL 포맷팅 활성화
        show_sql: true                    # 개발 환경에서는 SQL 출력 활성화
        generate_statistics: true         # 개발 환경에서는 통계 수집 활성화
    show-sql: true                        # 개발 환경에서는 SQL 출력 활성화
    open-in-view: true                    # 개발 환경에서는 OSIV 활성화 (디버깅 용이)

  # 개발 환경 Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 10000ms                   # 개발 환경에서는 긴 타임아웃
      password: ${REDIS_PASSWORD:#{null}}

# 개발 환경 JWT 설정
jwt:
  secret: ${JWT_SECRET:devSecretKeyForDevelopmentOnly123456789}
  token-validity-in-seconds: ${JWT_EXPIRATION:3600}      # 개발 환경에서는 1시간
  refresh-token-validity-in-days: ${JWT_REFRESH_EXPIRATION:30}   # 개발 환경에서는 30일
  cookie-name: ${JWT_COOKIE_NAME:sodam_jwt_dev}
  cookie-max-age: ${JWT_COOKIE_MAX_AGE:3600}

# 개발 환경 로깅 설정
logging:
  level:
    com.rich.sodam: DEBUG                 # 개발 환경에서는 DEBUG 레벨
    org.springframework.security: DEBUG  # 보안 관련 디버그
    org.springframework.cache: DEBUG     # 캐시 관련 디버그
    org.springframework.data.redis: DEBUG # Redis 관련 디버그
    org.hibernate.SQL: DEBUG             # SQL 쿼리 로깅
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # SQL 파라미터 로깅
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/sodam-dev.log

# 개발 환경 Swagger 설정
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    filter: true

# 개발 환경 Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"                      # 개발 환경에서는 모든 엔드포인트 노출
  endpoint:
    health:
      show-details: always                # 개발 환경에서는 상세 정보 항상 표시
  metrics:
    enabled: true                         # 개발 환경에서는 메트릭 활성화

# 개발 환경 국세청 API 설정
tax:
  office:
    api:
      key: ${NTS_API_KEY:dev_test_api_key}

# 개발 환경 전용 설정
app:
  dev:
    debug-mode: true
    test-data-enabled: true               # 개발 환경에서는 테스트 데이터 생성
    performance-monitoring: true          # 성능 모니터링 활성화
