spring:
  application:
    name: sodam
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:28f9c414aad345b18a52dc62a3373603}
            client-secret: ${KAKAO_CLIENT_SECRET:defaultSecret}
            redirect-uri: http://localhost:8080/kakao/auth/proc
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DB_URL:jdbc:mysql://localhost:3306/sodam?serverTime=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:#{null}}


    hikari:
      auto-commit: false
      transaction-isolation: TRANSACTION_READ_COMMITTED
      # 서버 비용 최적화를 위한 커넥션 풀 설정
      minimum-idle: 3                     # 유휴 상태로 유지할 최소 연결 수 (기존 5에서 감소)
      maximum-pool-size: 10               # 최대 연결 수 (기존 20에서 감소)
      idle-timeout: 300000                # 유휴 연결 제거 시간 (5분)
      max-lifetime: 1800000               # 연결 최대 수명 (30분)
      connection-timeout: 30000           # 연결 타임아웃 (30초)
      pool-name: SodamHikariPool          # 커넥션 풀 이름 (모니터링 용이)


  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}      # 운영 환경에서는 validate, 개발 환경에서는 create-drop 권장
    properties:
      hibernate:
        # 서버 비용 최적화를 위한 Hibernate 설정
        format_sql: false                 # 운영 환경에서는 비활성화 권장 (SQL 포맷팅 비용 절감)
        order_inserts: true               # 일괄 삽입 최적화
        order_updates: true               # 일괄 업데이트 최적화
        jdbc.batch_size: 30               # 배치 작업 크기 설정
        jdbc.batch_versioned_data: true   # 버전 관리 엔티티의 배치 처리 활성화
        query.in_clause_parameter_padding: true  # IN 절 파라미터 패딩 최적화
        query.plan_cache_max_size: 2048   # 쿼리 계획 캐시 크기 증가
        generate_statistics: false        # 통계 수집 비활성화 (성능 향상)
        cache:
          use_second_level_cache: true    # 2차 캐시 활성화
          use_query_cache: true           # 쿼리 캐시 활성화
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    open-in-view: false                   # OSIV 패턴 비활성화 (서버 리소스 최적화)
    show-sql: false                       # 운영 환경에서는 비활성화 권장 (로깅 비용 절감)
  aop:
    auto: true
    proxy-target-class: true
  transaction:
    default-timeout: 30s
  data:
    web:
      pageable:
        default-page-size: 20
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms
  cache:
    type: redis
    redis:
      time-to-live: 1800000  # 30분 기본 TTL
      cache-null-values: false
      key-prefix: "sodam:"
      use-key-prefix: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    groups-order: desc
    doc-expansion: none
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET:#{null}}
  token-validity-in-seconds: ${JWT_EXPIRATION:900}      # 15분 (액세스 토큰)
  refresh-token-validity-in-days: ${JWT_REFRESH_EXPIRATION:7}   # 7일 (리프레시 토큰)
  cookie-name: ${JWT_COOKIE_NAME:sodam_jwt}
  cookie-max-age: ${JWT_COOKIE_MAX_AGE:900}                 # 15분

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    enabled: false

# 국세청 사업자등록번호 조회 API 설정
tax:
  office:
    api:
      key: ${NTS_API_KEY:#{null}}  # 국세청 API 키
