-- V1 baseline — 엔티티 메타데이터에서 자동 생성(Hibernate MySQL 방언, SchemaBaselineTest).
-- 운영 신규 DB: Flyway 가 이 스크립트로 스키마 생성.
-- 기존 DB: baseline-on-migrate=true 로 V1 은 마커만 찍고 실행 생략, V2+ 만 적용.
-- 재생성: SchemaBaselineTest @Disabled 제거 후 schemagen 프로필 실행 → build/generated/V1__baseline.sql.

create table `labor_info` (`minimum_wage` integer, `overtime_rate` float(53), `weekly_max_hours` integer, `year` integer, `created_at` datetime(6) not null, `labor_info_id` bigint not null auto_increment, `updated_at` datetime(6), `content` varchar(255) not null, `image_path` varchar(255), `title` varchar(255) not null, primary key (`labor_info_id`)) engine=InnoDB;
create table `master_profile` (`user_id` bigint not null, `business_license_number` varchar(255), primary key (`user_id`)) engine=InnoDB;
create table `master_store_relation` (`id` bigint not null auto_increment, `master_id` bigint, `registered_at` datetime(6), `store_id` bigint, primary key (`id`)) engine=InnoDB;
create table `qna_info` (`created_at` datetime(6) not null, `qna_info_id` bigint not null auto_increment, `updated_at` datetime(6), `image_path` varchar(255), `question` varchar(255) not null, `title` varchar(255) not null, `answer` text, primary key (`qna_info_id`)) engine=InnoDB;
create table `tax_info` (`created_at` datetime(6) not null, `tax_info_id` bigint not null auto_increment, `updated_at` datetime(6), `content` varchar(255) not null, `image_path` varchar(255), `title` varchar(255) not null, primary key (`tax_info_id`)) engine=InnoDB;
create table `time_off` (`end_date` date, `start_date` date, `employee_id` bigint, `id` bigint not null auto_increment, `store_id` bigint, `reason` varchar(255), `status` enum ('APPROVED','PENDING','REJECTED'), primary key (`id`)) engine=InnoDB;
create table `tip_info` (`created_at` datetime(6) not null, `tip_info_id` bigint not null auto_increment, `updated_at` datetime(6), `content` varchar(255) not null, `image_path` varchar(255), `title` varchar(255) not null, primary key (`tip_info_id`)) engine=InnoDB;
create table `attendance` (`applied_hourly_wage` integer not null, `check_in_latitude` float(53), `check_in_longitude` float(53), `check_out_latitude` float(53), `check_out_longitude` float(53), `weekly_allowance` decimal(38,2), `attendance_id` bigint not null auto_increment, `check_in_time` datetime(6) not null, `check_out_time` datetime(6), `employee_id` bigint not null, `store_id` bigint not null, primary key (`attendance_id`)) engine=InnoDB;
create table `attendance_correction_request` (`acr_id` bigint not null auto_increment, `attendance_id` bigint not null, `decided_at` datetime(6), `proposed_check_in` datetime(6), `proposed_check_out` datetime(6), `requested_at` datetime(6) not null, `requester_id` bigint not null, `reason` varchar(200) not null, `reject_reason` varchar(255), `status` enum ('APPROVED','PENDING','REJECTED') not null, primary key (`acr_id`)) engine=InnoDB;
create table `device_token` (`created_at` datetime(6), `device_token_id` bigint not null auto_increment, `last_seen_at` datetime(6), `user_id` bigint not null, `token` varchar(500) not null, `platform` enum ('ANDROID','IOS','WEB') not null, primary key (`device_token_id`)) engine=InnoDB;
create table `employee_profile` (`end_weekly_allowance` date, `incomplete_week_allowance` decimal(38,2), `start_weekly_allowance` date, `user_id` bigint not null, `employee_number` varchar(255), primary key (`user_id`)) engine=InnoDB;
create table `employee_store_relation` (`custom_hourly_wage` integer, `hire_date` date, `is_active` bit not null, `use_store_standard_wage` bit, `employee_id` bigint, `id` bigint not null auto_increment, `store_id` bigint, `owner_memo` varchar(500), primary key (`id`)) engine=InnoDB;
create table `notification_inbox` (`is_read` bit not null, `created_at` datetime(6) not null, `notification_inbox_id` bigint not null auto_increment, `read_at` datetime(6), `user_id` bigint not null, `title` varchar(100) not null, `body` varchar(300) not null, `deep_link` varchar(300), `category` enum ('ATTENDANCE','BILLING','MARKETING','NOTICE','PAYROLL','SYSTEM') not null, primary key (`notification_inbox_id`)) engine=InnoDB;
create table `password_reset_token` (`used` bit not null, `created_at` datetime(6) not null, `expires_at` datetime(6) not null, `password_reset_token_id` bigint not null auto_increment, `email` varchar(100) not null, `reset_ticket` varchar(100) not null, `code_hash` varchar(200) not null, primary key (`password_reset_token_id`)) engine=InnoDB;
create table `payment_history` (`amount` integer not null, `billed_at` datetime(6) not null, `payment_history_id` bigint not null auto_increment, `subscription_id` bigint not null, `updated_at` datetime(6), `order_id` varchar(80) not null, `failure_reason` varchar(200), `payment_key` varchar(200), `status` enum ('FAILED','PENDING','REFUNDED','SUCCESS') not null, primary key (`payment_history_id`)) engine=InnoDB;
create table `payroll` (`base_hourly_wage` integer, `deductions` integer, `end_date` date, `gross_wage` integer, `net_wage` integer, `night_work_hours` float(53), `night_work_wage` integer, `overtime_hours` float(53), `overtime_wage` integer, `payment_date` date, `regular_hours` float(53), `regular_wage` integer, `start_date` date, `tax_amount` integer, `tax_rate` float(53), `weekly_allowance` integer, `created_at` datetime(6), `employee_id` bigint, `payroll_id` bigint not null auto_increment, `store_id` bigint, `updated_at` datetime(6), `cancel_reason` varchar(255), `status` enum ('CANCELLED','CONFIRMED','DRAFT','PAID'), primary key (`payroll_id`)) engine=InnoDB;
create table `payroll_detail` (`base_hourly_wage` integer, `daily_wage` integer, `end_time` time(6), `night_work_hours` float(53), `night_work_wage` integer, `overtime_hours` float(53), `overtime_wage` integer, `regular_hours` float(53), `regular_wage` integer, `start_time` time(6), `work_date` date, `attendance_id` bigint, `created_at` datetime(6), `id` bigint not null auto_increment, `payroll_id` bigint, `updated_at` datetime(6), `note` varchar(255), primary key (`id`)) engine=InnoDB;
create table `payroll_policy` (`night_work_rate` float(53), `night_work_start_time` time(6), `overtime_rate` float(53), `regular_hours_per_day` float(53), `weekly_allowance_enabled` bit, `created_at` datetime(6), `id` bigint not null auto_increment, `store_id` bigint, `updated_at` datetime(6), `tax_policy_type` enum ('FOUR_INSURANCES','INCOME_TAX_3_3'), primary key (`id`)) engine=InnoDB;
create table `personal_attendance` (`duration_minutes` integer, `check_in_at` datetime(6) not null, `check_out_at` datetime(6), `created_at` datetime(6) not null, `id` bigint not null auto_increment, `updated_at` datetime(6) not null, `user_id` bigint not null, `workplace_id` bigint, `note` varchar(500), primary key (`id`)) engine=InnoDB;
create table `personal_user_profile` (`default_hourly_wage` integer, `created_at` datetime(6) not null, `updated_at` datetime(6) not null, `user_id` bigint not null, `nickname` varchar(255), primary key (`user_id`)) engine=InnoDB;
create table `personal_workplace` (`hourly_wage` integer not null, `created_at` datetime(6) not null, `id` bigint not null auto_increment, `updated_at` datetime(6) not null, `user_id` bigint not null, `address` varchar(255), `name` varchar(255) not null, primary key (`id`)) engine=InnoDB;
create table `policy_info` (`created_at` datetime(6) not null, `policy_info_id` bigint not null auto_increment, `updated_at` datetime(6), `content` varchar(255) not null, `image_path` varchar(255), `title` varchar(255) not null, primary key (`policy_info_id`)) engine=InnoDB;
create table `referral` (`converted_at` datetime(6), `referee_user_id` bigint not null, `referral_id` bigint not null auto_increment, `referrer_user_id` bigint not null, `registered_at` datetime(6) not null, `referral_code` varchar(16) not null, `status` enum ('CANCELLED','CONVERTED','EXPIRED','REGISTERED') not null, primary key (`referral_id`)) engine=InnoDB;
create table `refresh_token` (`used` bit not null, `created_at` datetime(6) not null, `expiry_date` datetime(6) not null, `refresh_token_id` bigint not null auto_increment, `user_id` bigint not null, `token` varchar(500) not null, primary key (`refresh_token_id`)) engine=InnoDB;
create table `store` (`friday_close` time(6), `friday_is_closed` bit, `friday_open` time(6), `is_deleted` bit, `latitude` float(53), `longitude` float(53), `monday_close` time(6), `monday_is_closed` bit, `monday_open` time(6), `radius` integer not null, `saturday_close` time(6), `saturday_is_closed` bit, `saturday_open` time(6), `store_standard_hour_wage` integer not null, `sunday_close` time(6), `sunday_is_closed` bit, `sunday_open` time(6), `thursday_close` time(6), `thursday_is_closed` bit, `thursday_open` time(6), `tuesday_close` time(6), `tuesday_is_closed` bit, `tuesday_open` time(6), `wednesday_close` time(6), `wednesday_is_closed` bit, `wednesday_open` time(6), `created_at` datetime(6) not null, `deleted_at` datetime(6), `store_id` bigint not null auto_increment, `updated_at` datetime(6), `business_number` varchar(255) not null, `business_type` varchar(255) not null, `full_address` varchar(255), `jibun_address` varchar(255), `road_address` varchar(255), `store_code` varchar(255) not null, `store_name` varchar(255) not null, `store_phone_number` varchar(255) not null, primary key (`store_id`)) engine=InnoDB;
create table `store_photo` (`display_order` integer not null, `size_bytes` bigint, `store_id` bigint not null, `store_photo_id` bigint not null auto_increment, `uploaded_at` datetime(6) not null, `content_type` varchar(100), `storage_key` varchar(300) not null, `public_url` varchar(500) not null, primary key (`store_photo_id`)) engine=InnoDB;
create table `subscription` (`payment_failure_count` integer not null, `cancelled_at` datetime(6), `created_at` datetime(6) not null, `current_period_end_at` datetime(6), `current_period_start_at` datetime(6), `expired_at` datetime(6), `next_billing_at` datetime(6), `started_at` datetime(6), `subscription_id` bigint not null auto_increment, `updated_at` datetime(6), `user_id` bigint not null, `card_label` varchar(60), `customer_key` varchar(60) not null, `billing_key` varchar(200), `plan` enum ('BUSINESS','COMMISSION','FREE','PREMIUM') not null, `status` enum ('ACTIVE','CANCELLED','EXPIRED','PAST_DUE','PENDING_PAYMENT') not null, primary key (`subscription_id`)) engine=InnoDB;
create table `user` (`birth_date` date, `age_confirmed_at` datetime(6), `created_at` datetime(6) not null, `marketing_agreed_at` datetime(6), `privacy_agreed_at` datetime(6), `profile_completed_at` datetime(6), `terms_agreed_at` datetime(6), `user_id` bigint not null auto_increment, `phone` varchar(20), `name` varchar(50) not null, `email` varchar(100) not null, `password` varchar(255), `user_grade` enum ('BOSSES','EMPLOYEE','MANAGER','MASTER','Personal') not null, primary key (`user_id`)) engine=InnoDB;
create table `wage_history` (`effective_from` date not null, `hourly_wage` integer not null, `changed_by_user_id` bigint, `created_at` datetime(6) not null, `employee_id` bigint, `store_id` bigint not null, `wage_history_id` bigint not null auto_increment, `reason` varchar(200), `scope` enum ('EMPLOYEE_OVERRIDE','STORE_DEFAULT') not null, primary key (`wage_history_id`)) engine=InnoDB;
create index idx_attendance_employee_id on `attendance` (`employee_id`);
create index idx_attendance_store_id on `attendance` (`store_id`);
create index idx_attendance_check_in_time on `attendance` (`check_in_time`);
create index idx_attendance_check_out_time on `attendance` (`check_out_time`);
create index idx_attendance_employee_store on `attendance` (`employee_id`, `store_id`);
create index idx_attendance_date_range on `attendance` (`check_in_time`, `check_out_time`);
create index idx_acr_attendance on `attendance_correction_request` (`attendance_id`);
create index idx_acr_status on `attendance_correction_request` (`status`);
create index idx_acr_requested_at on `attendance_correction_request` (`requested_at`);
create index idx_device_token_user on `device_token` (`user_id`);
alter table `device_token` add constraint idx_device_token_token unique (`token`);
create index idx_employee_number on `employee_profile` (`employee_number`);
create index idx_employee_user_id on `employee_profile` (`user_id`);
create index idx_employee_weekly_allowance on `employee_profile` (`start_weekly_allowance`, `end_weekly_allowance`);
create index idx_employee_store on `employee_store_relation` (`employee_id`, `store_id`);
create index idx_employee_id on `employee_store_relation` (`employee_id`);
create index idx_store_id on `employee_store_relation` (`store_id`);
create index idx_hire_date on `employee_store_relation` (`hire_date`);
create index idx_wage_settings on `employee_store_relation` (`use_store_standard_wage`, `custom_hourly_wage`);
create index idx_notif_inbox_user on `notification_inbox` (`user_id`, `created_at`);
create index idx_notif_inbox_read on `notification_inbox` (`user_id`, `is_read`);
create index idx_pwd_reset_email on `password_reset_token` (`email`);
create index idx_pwd_reset_expires_at on `password_reset_token` (`expires_at`);
alter table `password_reset_token` add constraint idx_pwd_reset_code_hash unique (`code_hash`);
alter table `password_reset_token` add constraint `UKdb5fs3jkv80ywgjgkydne3yob` unique (`reset_ticket`);
create index idx_payment_history_subscription on `payment_history` (`subscription_id`);
create index idx_payment_history_status on `payment_history` (`status`);
create index idx_payment_history_billed_at on `payment_history` (`billed_at`);
alter table `payment_history` add constraint `UKkbdixbaydqero4r5xqvw5ripn` unique (`order_id`);
alter table `payroll_detail` add constraint `UKk9i51ba7hdxdqmp1qhmv7l5a` unique (`attendance_id`);
alter table `payroll_policy` add constraint `UK21ifpyv7bm3kl2lwvtumr38k8` unique (`store_id`);
create index idx_pa_user_id_id_desc on `personal_attendance` (`user_id`, `id`);
create index idx_pa_user_check_in on `personal_attendance` (`user_id`, `check_in_at`);
create index idx_pw_user_id_id_desc on `personal_workplace` (`user_id`, `id`);
create index idx_referral_referrer on `referral` (`referrer_user_id`);
create index idx_referral_referee on `referral` (`referee_user_id`);
create index idx_referral_status on `referral` (`status`);
alter table `referral` add constraint idx_referral_code unique (`referral_code`);
alter table `refresh_token` add constraint `UKjt03h16a914amgbg67hicpcu6` unique (`token`);
create index idx_store_business_number on `store` (`business_number`);
create index idx_store_code on `store` (`store_code`);
create index idx_store_name on `store` (`store_name`);
create index idx_store_location on `store` (`latitude`, `longitude`);
create index idx_store_created_at on `store` (`created_at`);
create index idx_store_updated_at on `store` (`updated_at`);
create index idx_store_is_deleted on `store` (`is_deleted`);
create index idx_store_deleted_at on `store` (`deleted_at`);
alter table `store` add constraint `UK2odibf2q8sm6csobnihntu5u7` unique (`business_number`);
alter table `store` add constraint `UKhjqtkjraqjra5equxixndgryw` unique (`store_code`);
create index idx_store_photo_store on `store_photo` (`store_id`, `display_order`);
create index idx_subscription_user on `subscription` (`user_id`);
create index idx_subscription_status on `subscription` (`status`);
create index idx_subscription_next_billing on `subscription` (`next_billing_at`);
create index idx_user_email on `user` (`email`);
create index idx_user_grade on `user` (`user_grade`);
create index idx_user_created_at on `user` (`created_at`);
alter table `user` add constraint `UKoshmjvr6wht0bg9oivn75aajr` unique (`email`);
create index idx_wage_history_store on `wage_history` (`store_id`, `effective_from`);
create index idx_wage_history_employee on `wage_history` (`employee_id`, `store_id`, `effective_from`);
alter table `master_profile` add constraint `FKm68y0u53nwnlour74u8axcv3p` foreign key (`user_id`) references `user` (`user_id`);
alter table `master_store_relation` add constraint `FKi3nkbjiofbvn279vknept8kcj` foreign key (`master_id`) references `master_profile` (`user_id`);
alter table `master_store_relation` add constraint `FKm3shbjwdmcnjwflgd89p9eq6o` foreign key (`store_id`) references `store` (`store_id`);
alter table `time_off` add constraint `FKpxfgh2prfe18g0948gq5jym0h` foreign key (`employee_id`) references `employee_profile` (`user_id`);
alter table `time_off` add constraint `FK4uhk1idnylvlntyhbmickk830` foreign key (`store_id`) references `store` (`store_id`);
alter table `attendance` add constraint `FK80tnowr70ho2pev6x1ltjtlff` foreign key (`employee_id`) references `employee_profile` (`user_id`);
alter table `attendance` add constraint `FKipujw0lxf9k320rvbkeoukkl8` foreign key (`store_id`) references `store` (`store_id`);
alter table `attendance_correction_request` add constraint `FKbyen5xbqdhda1ue2qphopwmr0` foreign key (`attendance_id`) references `attendance` (`attendance_id`);
alter table `attendance_correction_request` add constraint `FK4iccng5n0xq7ksojhq3f06j9` foreign key (`requester_id`) references `user` (`user_id`);
alter table `device_token` add constraint `FK2vygpe4ihcmfjpudhog6xk6af` foreign key (`user_id`) references `user` (`user_id`);
alter table `employee_profile` add constraint `FKhc5h3msr43jly06gilpoljosr` foreign key (`user_id`) references `user` (`user_id`);
alter table `employee_store_relation` add constraint `FKkvnwkuxr5b1lro5msfl7ypvv7` foreign key (`employee_id`) references `employee_profile` (`user_id`);
alter table `employee_store_relation` add constraint `FKgxmodbfxpdsgpbt1mvt6px982` foreign key (`store_id`) references `store` (`store_id`);
alter table `notification_inbox` add constraint `FKlhvemjhawxkpetu3rm229c8iw` foreign key (`user_id`) references `user` (`user_id`);
alter table `payment_history` add constraint `FKjl3kd10b7faarg56yljycfan2` foreign key (`subscription_id`) references `subscription` (`subscription_id`);
alter table `payroll` add constraint `FK7pn18jtdqrcn6n954793l2dou` foreign key (`employee_id`) references `employee_profile` (`user_id`);
alter table `payroll` add constraint `FKj00i4m5yhyhustlbj0p2c7vx7` foreign key (`store_id`) references `store` (`store_id`);
alter table `payroll_detail` add constraint `FK337rm0cjcc7svepwmyq94xtai` foreign key (`attendance_id`) references `attendance` (`attendance_id`);
alter table `payroll_detail` add constraint `FK5joa1k7k3k9f9ue8odjnne3l7` foreign key (`payroll_id`) references `payroll` (`payroll_id`);
alter table `payroll_policy` add constraint `FKoq4nveceevqgxn2ow94iu6yct` foreign key (`store_id`) references `store` (`store_id`);
alter table `referral` add constraint `FKag8q0as5xk0jgk2c8jxvhuboc` foreign key (`referee_user_id`) references `user` (`user_id`);
alter table `referral` add constraint `FKobxr25xm7o0l3vf0hpt0c5kt4` foreign key (`referrer_user_id`) references `user` (`user_id`);
alter table `refresh_token` add constraint `FKeue2q8nms1ytt8lt3tmukg6ps` foreign key (`user_id`) references `user` (`user_id`);
alter table `store_photo` add constraint `FKta18x5hnf5sfxjqjo7gb3th0g` foreign key (`store_id`) references `store` (`store_id`);
alter table `subscription` add constraint `FKbf8h5kfsyuiwhvowaq1tpkglr` foreign key (`user_id`) references `user` (`user_id`);
alter table `wage_history` add constraint `FKfiohy4bnpu0pf34bmnwye8b4a` foreign key (`changed_by_user_id`) references `user` (`user_id`);
alter table `wage_history` add constraint `FKq2te4q5ij79nngb9in6bkojow` foreign key (`employee_id`) references `employee_profile` (`user_id`);
alter table `wage_history` add constraint `FK1o27uv85y9cylncnod2oihs2` foreign key (`store_id`) references `store` (`store_id`);
